# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
  export ARM_SUBSCRIPTION_ID=$(azSubID)
  export ARM_TENANT_ID=$(azTenantID)
  export ARM_CLIENT_ID=$(azClientID)
  export ARM_CLIENT_SECRET=$(azClientSecret)
  # Download Tenable CS CLI
  wget https://downloads.accurics.com/cli/latest/accurics_linux -O tcs-iac-scanner
  chmod +x tcs-iac-scanner
  ./tcs-iac-scanner init
  ./tcs-iac-scanner plan -mode=pipeline -appurl=https://cloud.tenable.com/cns -token=<tcs_api_token> -fail -project=<project_id>

- script: |
  export ARM_SUBSCRIPTION_ID=$(azSubID)
  export ARM_TENANT_ID=$(azTenantID)
  export ARM_CLIENT_ID=$(azClientID)
  export ARM_CLIENT_SECRET=$(azClientSecret)
  # Download Tenable CS CLI
  wget https://downloads.accurics.com/cli/latest/accurics_linux -O tcs-iac-scanner
  chmod +x tcs-iac-scanner
  ./tcs-iac-scanner init
  ./tcs-iac-scanner scan -mode=pipeline -appurl=https://cloud.tenable.com/cns -token=<tcs_api_token> -fail -project=<project_id>
